# Generated by Django 3.1.6 on 2021-02-17 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20210216_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 1, 36, 19, 595131), verbose_name='Date'),
        ),
    ]
