# Generated by Django 3.1.6 on 2021-02-17 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20210217_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 1, 39, 7, 379217), verbose_name='Date'),
        ),
    ]
