# Generated by Django 3.1.6 on 2021-02-17 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_auto_20210217_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 23, 7, 23, 179850), verbose_name='Date'),
        ),
    ]
