# Generated by Django 3.1.6 on 2021-02-18 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0013_auto_20210218_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 18, 19, 58, 15, 522049), verbose_name='Date'),
        ),
    ]
