# Generated by Django 3.1.6 on 2021-02-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(choices=[('CL', 'CHILE'), ('PR', 'PERU')], default='CL', max_length=2),
        ),
    ]
