# Generated by Django 3.1.6 on 2021-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='create_at',
            field=models.DateField(default='2021-02-18', verbose_name='Date'),
        ),
    ]
