# Generated by Django 3.1.6 on 2021-02-16 20:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_at', models.DateField(default=datetime.datetime(2021, 2, 16, 20, 14, 13, 269407), verbose_name='Date of published')),
                ('create_at', models.DateField(default=datetime.datetime(2021, 2, 16, 20, 14, 13, 269417), verbose_name='Date')),
                ('lunches', models.ManyToManyField(to='lunch.Lunch')),
            ],
            options={
                'ordering': ['published_at'],
            },
        ),
    ]
