# Generated by Django 3.1.6 on 2021-02-16 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 20, 14, 44, 344779), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 20, 14, 44, 344769), verbose_name='Date of published'),
        ),
    ]
