# Generated by Django 3.1.6 on 2021-02-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210216_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='create_at',
            field=models.DateField(default='2021-02-17', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='published_at',
            field=models.DateField(default='2021-02-17', verbose_name='Date of published'),
        ),
    ]
