# Generated by Django 3.1.6 on 2021-02-16 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210216_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 20, 20, 53, 221137), verbose_name='Date'),
        ),
    ]
