# Generated by Django 3.1.6 on 2021-02-17 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210217_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 22, 59, 7, 640346), verbose_name='Date'),
        ),
    ]
