# Generated by Django 3.1.6 on 2021-02-17 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210217_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='applicant_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 17, 23, 12, 2, 485420), verbose_name='Date'),
        ),
    ]
