# Generated by Django 3.1.6 on 2021-02-18 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210217_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 18, 0, 52, 1, 259146), verbose_name='Date'),
        ),
    ]
