# Generated by Django 3.1.6 on 2021-02-21 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210221_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 23, 47, 19, 512581), verbose_name='Date'),
        ),
    ]
